### PR TITLE
Added pokemon moves

### PR DESCRIPTION
**Pull request by wgranados**

### CODE REVIEW

**Comment by purpasmart96** [comment]
Looks like you put in the wrong file, oh well I'm merging it anyway

**Comment by wgranados** [comment]
oh woops, my bad.

**Comment by wgranados** [comment]
Oh, and I sorted the variables in the enum.
Was that the change that you wanted? or was it something else.

**Comment by wgranados** [comment]
Oh, I just found the changes you made.
they were in the .h files.

**Comment by wgranados** [comment]
Just learned what .h files are.
I'll move my changes there.

**Comment by purpasmart96** [comment]
Put typedef in front of the enum

**Pull request merged**
